# Generated by Django 3.1.3 on 2020-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group14', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default='My Bio', max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bio',
            field=models.TextField(blank=True, default='My Bio', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
