# Generated by Django 3.1.3 on 2020-11-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group14', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
