# Generated by Django 3.1.3 on 2020-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group14', '0002_auto_20201116_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50, unique=True),
        ),
    ]
