# Generated by Django 3.1.3 on 2020-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group14', '0003_auto_20201113_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
