# Generated by Django 3.1.3 on 2020-11-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group14', '0004_auto_20201117_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
